name: Bonjour
on:
  - push
jobs.container.options:
  dire_bonjour:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/cicd-lectures/gitpod:latest
    steps:
      - uses: actions/checkout@v5
      - run: ls -l
      - run: cat README.md | cowsay