name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/cicd-lectures/gitpod:latest
      options: --user=root
    steps:
      - uses: actions/checkout@v5
      - run: ls -l

      - name: cowsay
        id: cosway_output_id
        run: cat README.md | cowsay
        with:
          path: ./README.md 

      - name: Echo package.json
        run: echo "${{ steps.cowsay_output_id.outputs.cowsay }}"