name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - run: apt-get install cowsay
      - run: ls -l  
      - run: cat README.md | cowsay